# Will an error occur if you try to access a list element with an index greater than or equal to 
# the list's length? For example:

foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error?

# Yes, it will give an IndexError: out of range as the index[3] does not exist in the given 'foo' 
# list. 
